### ISSUE TITLE
Refunding Request Obj is sometimes wrong

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-adyen-integration#1052]
When performing refunds (our DEV examples below) we are seeing that sometimes these fail and produce the following requests (taken from the interface interactions):

```
{
            "type": {
                "typeId": "type",
                "id": "4c19a616-a212-4d14-bc0c-4b569c3e36fc"
            },
            "fields": {
                "createdAt": "2022-12-28T22:15:59.930Z",
                "response": "{\"name\":\"SyntaxError\",\"message\":\"Unexpected token M in JSON at position 4\",\"stack\":\"SyntaxError: Unexpected token M in JSON at position 4\\n    at JSON.parse (<anonymous>)\\n    at Response.json (file:///app/node_modules/node-fetch/src/body.js:149:15)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async fetchAsync (file:///app/src/service/web-component-service.js:216:24)\\n    at async callAdyen (file:///app/src/service/web-component-service.js:182:35)\\n    at async file:///app/src/paymentHandler/refund-payment.handler.js:37:37\\n    at async Promise.all (index 0)\\n    at async Object.execute (file:///app/src/paymentHandler/refund-payment.handler.js:24:3)\\n    at async Promise.all (index 0)\"}",
                "request": "{\"body\":\"{\\\"modificationAmount\\\":{\\\"value\\\":1,\\\"currency\\\":\\\"GBP\\\"},\\\"originalReference\\\":\\\"T4ZNQZZTCV5X8N82\\\",\\\"reference\\\":\\\"a810873b-e394-45d1-9a61-c4a2a24b0d12\\\",\\\"metadata\\\":{\\\"ctProjectKey\\\":\\\"fa-compcomm-dev\\\"},\\\"merchantAccount\\\":\\\"S0115_Kings-Will-Dream-Web\\\"}\"}",
                "type": "refund"
            }
        }
```

Most of the time this works resulting in an interface interaction such as:

```
{
            "type": {
                "typeId": "type",
                "id": "4c19a616-a212-4d14-bc0c-4b569c3e36fc"
            },
            "fields": {
                "createdAt": "2022-12-28T22:15:42.032Z",
                "response": "{\"pspReference\":\"NDJBCR5QC3RZNN82\",\"response\":\"[refund-received]\"}",
                "request": "{\"modificationAmount\":{\"value\":50,\"currency\":\"GBP\"},\"originalReference\":\"T4ZNQZZTCV5X8N82\",\"reference\":\"a810873b-e394-45d1-9a61-c4a2a24b0d12\",\"metadata\":{\"ctProjectKey\":\"fa-compcomm-dev\"},\"merchantAccount\":\"S0115_Kings-Will-Dream-Web\"}",
                "type": "refund"
            }
        }
```

We looked thru the code and cannot figure out why the extension would add `"{\"body\":\" ` sometimes and not others. We don't know if we are doing something wrong with our requests but they seem fine, in commercetools we send a Refund Transaction draft as per the [guide](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/Refund.md). Sometimes they work and then other times we get this quite randomly.

Please help, as this is creating some painful admin problems.

**Comment by praveenkumarct** [comment]
Hello @BielsasBucket , 
Thank you for reporting the issue.
We will check and let you know.

**Comment by leungkinghin** [comment]
@BielsasBucket Thank you for your reporting.
We found that the `"{\"body\":\" ` attribute is added only after error is thrown out during communication between this integration and Adyen API.
https://github.com/commercetools/commercetools-adyen-integration/blob/b8d6e25a242d70ef6124d1a9af5e1f9fc447b6c8/extension/src/service/web-component-service.js#L192
That means, `body` attribute is just the displayed result of the error, not the cause of the error.

Also, based on the response you provided, it is about non-json format response returned by adyen api, which is not expected. 

We will check it with Adyen and see how we can handle this case.

**Comment by BielsasBucket** [comment]
Hi, so is this occurring as Adyen when refunding is returning a "non-Json response"? Do you happen to know what that might be? Also, are there plans to handle this in the extension?

**Comment by leungkinghin** [comment]
We don't know the true cause at this moment since it got hidden by json parsing error.
Before we are going to handle this in extension, we would discuss with Adyen and make sure why response can be non-JSON format since it is not expected all the time.

**Comment by BielsasBucket** [comment]
Thank you, I'll ensure we are always checking the response and acting accordingly.

**Comment by leungkinghin** [comment]
We will let you know the result once we come up with a solution for that. thx

**Comment by leungkinghin** [comment]
@BielsasBucket We have talked with Adyen technical team. They said they can investigate the case from data history stored 7 days ago.

May I know if you have this problem in the last 7 days?

**Comment by BielsasBucket** [comment]
As far as I have been able to check their haven't been issues in the last 7 days. Most of the issues occurred in both **TEST** and **LIVE** environments in the first 2-3 weeks in December.

**Comment by BielsasBucket** [comment]
@leungkinghin - we are having those issues again today in the TEST (fa-compcomm-dev) environment on Adyen. We have deployed code in our services to change the REFUND transaction state from INITIAL to FAILURE when this happens.

Payment IDs:

- 1fd63bed-45d8-4c56-9c7c-ca1407e1bbb4 [Time of Update: 2023-01-12T16:08:10.546Z]
- e7ceb89f-5075-48a0-8f82-7246f008c857 [2023-01-12T14:48:35.346Z]
- 36db3b3a-591f-4646-800a-28a2988a3474 [2023-01-12T14:35:42.145Z and tried again at 2023-01-12T14:37:52.245Z]
- 0f4bd117-4439-42fb-aa24-7cebd54244f8 [2023-01-12T14:33:50.245Z]
- 9b8dfb8d-40f6-4274-9e3e-2a60fae8c4bd [2023-01-12T14:30:00.246Z]
- 3fcf70e5-ca92-406b-a5e6-2441fa7831e3 [2023-01-12T14:21:23.645Z]

**Comment by BielsasBucket** [comment]
@leungkinghin - Payment Ids [Time of Refund][PSP Reference for the payment we are trying to refund]

- 1fd63bed-45d8-4c56-9c7c-ca1407e1bbb4 [2023-01-12T16:08:10.546Z] [GZRZZGR2CKMLNK82]
- e7ceb89f-5075-48a0-8f82-7246f008c857 [2023-01-12T14:48:35.346Z][CXFFJB2DTXSKGK82]
- 36db3b3a-591f-4646-800a-28a2988a3474 [2023-01-12T14:35:42.145Z and tried again at 2023-01-12T14:37:52.245Z][HFBM9HQ3975ZGN82]
- 0f4bd117-4439-42fb-aa24-7cebd54244f8 [2023-01-12T14:33:50.245Z][JJT9J78727TG5S82]
- 9b8dfb8d-40f6-4274-9e3e-2a60fae8c4bd [2023-01-12T14:30:00.246Z][F97G4RP2CKMLNK82]
- 3fcf70e5-ca92-406b-a5e6-2441fa7831e3 [2023-01-12T14:21:23.645Z][NSNHCJCTPRWZNN82]

We don't have any PSP references for the refund as it is not getting that far, if that makes sense, as Adyen just returns garbage when making the request to refund.

**Comment by leungkinghin** [comment]
> We don't have any PSP references for the refund as it is not getting that far, if that makes sense, as Adyen just returns garbage when making the request to refund.

@BielsasBucket Understood. We received psp reference after we did the `makePayment` process, and it would be used as `originalReference` in refund request, so this one supposed to be enough for Adyen to check it.

**Comment by BielsasBucket** [comment]
No worries, sent them over. We are still having this issue over night in DEV too, out nightly build recorded it.

Payment Id [time of refund attempt][PSP]

- 3f2d3f43-ce8c-41ae-b7b3-172aef41a6cd [2023-01-13T07:43:27.646Z][**MKW736V727TG5S82**]

**Comment by leungkinghin** [comment]
Have already sent them the reference numbers. Once Adyen technical support has finished the investigation, we would update you. Thank you.

**Comment by TheMayorofMeltham** [comment]
Morning, have you got a ticket number I can send to Adyen to chase up please?

**Comment by leungkinghin** [comment]
@BielsasBucket @TheMayorofMeltham 
We have got the reply from Adyen Technical Team as following

> Thanks for providing us with the references.
>  
> I can confirm we are sending you back the right information in the correct format.
>  
> Attaching 1 example request/response for your reference.
>  ```
> {
>    "modificationAmount" : {
>       "value" : 50,
>       "currency" : "GBP"
>    },
>    "originalReference" : "CXFFJB2DTXSKGK82",
>    "reference" : "e7ceb89f-5075-48a0-8f82-7246f008c857",
>    "metadata" : {
>       "ctProjectKey" : "fa-compcomm-dev"
>    },
>    "merchantAccount" : "S0016_FA_Web"
> }
>  ```
> ```
> {
>    "pspReference" : "LMBZRH4DTXSKGK82",
>    "response" : "[refund-received]"
> }
>  ```
> The error you are seeing is not really coming from us and we haven't seen any other merchant reaching out to us that we provided them response in non json format.

Regarding this case, our team has arranged a task in upcoming weeks to handle any non-Json format response from Adyen, so that we can understand more what actually has happened. Hope it can help us to follow-up with Adyen later on.

**Comment by davidsimpson-footasylum** [comment]
Hi, that example Adyen have given you is from 15th December.

> "id": "4737181c-1d1b-4d53-aa93-f80c7f070140",
>             "timestamp": "2022-12-15T17:13:32.000Z",
>             "type": "Refund",
>             "amount": {
>                 "type": "centPrecision",
>                 "currencyCode": "GBP",
>                 "centAmount": 50,
>                 "fractionDigits": 2
>             },
>             "interactionId": "LMBZRH4DTXSKGK82",
>             "state": "Success" 

It seems they've been very selective in their response to you. There are other refund attempts against that payment failed but they've not looked at that. This only started being an issue on all refund attempts around midday on Thursday 12th Jan 2023.
[payment-3f2d3f43-ce8c-41ae-b7b3-172aef41a6cd.txt](https://github.com/commercetools/commercetools-adyen-integration/files/10425945/payment-3f2d3f43-ce8c-41ae-b7b3-172aef41a6cd.txt)

**Comment by BielsasBucket** [comment]
@leungkinghin

Payment Id [time of refund attempt][PSP]

3f2d3f43-ce8c-41ae-b7b3-172aef41a6cd [2023-01-13T07:43:27.646Z][**MKW736V727TG5S82**]

Below is an example of the interface interaction for the refund.

```
        {
            "type": {
                "typeId": "type",
                "id": "4c19a616-a212-4d14-bc0c-4b569c3e36fc"
            },
            "fields": {
                "createdAt": "2023-01-13T07:43:27.646Z",
                "response": "{\"name\":\"SyntaxError\",\"message\":\"Unexpected token M in JSON at position 4\",\"stack\":\"SyntaxError: Unexpected token M in JSON at position 4\\n    at JSON.parse (<anonymous>)\\n    at Response.json (file:///app/node_modules/node-fetch/src/body.js:149:15)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async fetchAsync (file:///app/src/service/web-component-service.js:216:24)\\n    at async callAdyen (file:///app/src/service/web-component-service.js:182:35)\\n    at async file:///app/src/paymentHandler/refund-payment.handler.js:37:37\\n    at async Promise.all (index 0)\\n    at async Object.execute (file:///app/src/paymentHandler/refund-payment.handler.js:24:3)\\n    at async Promise.all (index 0)\"}",
                "request": "{\"body\":\"{\\\"modificationAmount\\\":{\\\"value\\\":1000,\\\"currency\\\":\\\"GBP\\\"},\\\"originalReference\\\":\\\"MKW736V727TG5S82\\\",\\\"reference\\\":\\\"3f2d3f43-ce8c-41ae-b7b3-172aef41a6cd\\\",\\\"metadata\\\":{\\\"ctProjectKey\\\":\\\"fa-compcomm-dev\\\"},\\\"merchantAccount\\\":\\\"S0016_FA_Web\\\"}\"}",
                "type": "refund"
            }
        }
```

This request is made as per the guides and works the vast majority of the time, except when it doesn't. The other payment ids, I have sent in the past are all basically the same request/response with the slight differences of the the original reference and reference.

We have coded a "fix" to ensure when this happens the transaction state is changed from **initial** to **failed** but if you can do something that would help too.

I would also note Adyen appear not to have looked at the PSP references we sent to you. I know from personal experience, getting to look at what you actually ask is very difficult. Clearly, they are not sending the response in a format expected. 

Hope this helps and thanks for all the effort so far.

**Comment by leungkinghin** [comment]
@davidsimpson-footasylum Thank you for your findings. I have just asked Adyen support to investigate the refund request again since the response is created in December and doesn't match with the request.

@BielsasBucket Thank you for your sharing. I have sent the entire request to Adyen tech support and told them we are unable to convert the response into JSON. Let's wait for the Adyen tech support's reply.

Meanwhile we would start working on non-JSON response handling this two weeks so that we can have more details about the incorrect refund response format.

**Comment by leungkinghin** [comment]
@BielsasBucket We have already published a new release as enhancement.
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v10.1.2

Now the non-JSON response would be included in error stack and saved as `response` attribute in `InterfaceInteraction`, so that the root cause from the Adyen API call can be revealed.

Please feel free to let us know if you find refund error with the new release. We can investigate it with Adyen support.

**Comment by BielsasBucket** [comment]
Thanks, will do. Will try and release this as soon as possible.

**Comment by BielsasBucket** [comment]
Upgraded and the messages are clear when this happens. Thank you!
