### ISSUE TITLE
Fix flaky timeout in e2e tests

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-adyen-integration#415]
Possible solution: check the logs and try to increase the timeouts for selectors. The flaky tests is blocking the dependencies are updated.

Example log:
```
1) ::klarnaPayment::
       when payment method is klarna and process is done correctly, then it should successfully finish the payment:
     TimeoutError: waiting for selector "#redirect-response" failed: timeout 30000ms exceeded
      at new WaitTask (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/DOMWorld.js:407:34)
      at DOMWorld._waitForSelectorOrXPath (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/DOMWorld.js:332:26)
      at DOMWorld.waitForSelector (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/DOMWorld.js:315:21)
      at Frame.waitForSelector (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/FrameManager.js:384:51)
      at Frame.<anonymous> (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/helper.js:117:27)
      at Page.waitForSelector (/home/travis/build/commercetools/commercetools-adyen-integration/extension/node_modules/puppeteer/lib/Page.js:867:33)
      at handleRedirect (/home/travis/build/commercetools/commercetools-adyen-integration/extension/test/e2e/klarna.spec.js:111:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Context.<anonymous> (/home/travis/build/commercetools/commercetools-adyen-integration/extension/test/e2e/klarna.spec.js:64:40)
```

**Comment by ahmetoz** [comment]
This error is not happening anymore, probably fixed in another PR.
