### ISSUE TITLE
createdAt on addInterfaceInteraction action is empty

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-adyen-integration#75]
We got this error in a notification module where `createdAt={}`. This returns error from the platform:
```json
{
  "code": 502,
  "statusCode": 502,
  "status": 502,
  "message": "'500' is not an expected status code.",
  "originalRequest": {
    "uri": "/our-demo-project/payments/9ff06372-4812-4293-916b-01c58864c056",
    "method": "POST",
    "body": {
      "version": 101,
      "actions": [
        {
          "action": "addInterfaceInteraction",
          "type": {
            "key": "ctp-adyen-integration-interaction-notification",
            "typeId": "type"
          },
          "fields": {
            "createdAt": {},
            "status": "AUTHORISATION",
            "notification": "{\"NotificationRequestItem\":{\"additionalData\":{\"expiryDate\":\"10/2020\",\"authCode\":\"39697\",\"cardSummary\":\"1142\"},\"amount\":{\"currency\":\"EUR\",\"value\":495},\"eventCode\":\"AUTHORISATION\",\"eventDate\":\"2019-07-03T19:19:30+02:00\",\"merchantAccountCode\":\"CommercetoolsGmbHDE775\",\"merchantReference\":\"paymentReferenceId\",\"operations\":[\"CANCEL\",\"CAPTURE\",\"REFUND\"],\"paymentMethod\":\"visa\",\"pspReference\":\"853562174370815K\",\"reason\":\"39697:1142:10/2020\",\"success\":\"true\"}}"
          }
        }
      ]
    },
    "headers": {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "Authorization": [
        "Bearer ********"
      ]
    }
  },
  "retryCount": 0,
  "headers": {
    "server": [
      "nginx"
    ],
    "date": [
      "Fri, 05 Jul 2019 22:04:19 GMT"
    ],
    "content-type": [
      "application/json; charset=utf-8"
    ],
    "content-length": [
      "337"
    ],
    "x-http-status-caused-by-extension": [
      "true"
    ],
    "server-timing": [
      "projects;dur=74"
    ],
    "x-correlation-id": [
      "projects-c055bbda-12ee-45d2-9b53-09e9f02fc4a4"
    ],
    "x-served-by": [
      "api-gce-bf772e57.sphere.prod.commercetools.de"
    ],
    "x-served-config": [
      "sphere-projects-ws-1.0"
    ],
    "access-control-allow-origin": [
      "*"
    ],
    "access-control-allow-headers": [
      "Accept, Authorization, Content-Type, Origin, User-Agent"
    ],
    "access-control-allow-methods": [
      "GET, POST, DELETE, OPTIONS"
    ],
    "access-control-max-age": [
      "299"
    ],
    "via": [
      "1.1 google"
    ],
    "alt-svc": [
      "clear"
    ],
    "connection": [
      "close"
    ]
  },
  "body": {
    "statusCode": 502,
    "message": "'500' is not an expected status code.",
    "errors": [
      {
        "code": "ExtensionBadResponse",
        "message": "'500' is not an expected status code.",
        "extensionErrors": [],
        "extensionBody": "",
        "extensionStatusCode": 500,
        "extensionId": "42ffdeb9-70c7-4630-b033-3de4b91886f2",
        "extensionKey": "ctp-adyen-integration-payment-extension"
      }
    ]
  },
  "name": "HttpError",
  "stack": "HttpError: '500' is not an expected status code.\\n    at createError (/app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:236:10)\\n    at /app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:341:25\\n    at <anonymous>\\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
}
```

The complete log:
```json
{
  "insertId": "sb6tfrf832tku",
  "jsonPayload": {
    "hostname": "xxx",
    "adyenRequestBody": "{\"live\":\"false\",\"notificationItems\":[{\"NotificationRequestItem\":{\"additionalData\":{\"expiryDate\":\"10\\/2020\",\"authCode\":\"39697\",\"cardSummary\":\"1142\"},\"amount\":{\"currency\":\"EUR\",\"value\":495},\"eventCode\":\"AUTHORISATION\",\"eventDate\":\"2019-07-03T19:19:30+02:00\",\"merchantAccountCode\":\"CommercetoolsGmbHDE775\",\"merchantReference\":\"paymentReferenceId\",\"operations\":[\"CANCEL\",\"CAPTURE\",\"REFUND\"],\"paymentMethod\":\"visa\",\"pspReference\":\"853562174370815K\",\"reason\":\"39697:1142:10\\/2020\",\"success\":\"true\"}}]}",
    "level": 50,
    "name": "ctp-adyen-integration-notifications",
    "v": 0,
    "err": {
      "message": "Unexpected error during updating a payment with ID: 9ff06372-4812-4293-916b-01c58864c056. Exiting. Error: {\"code\":502,\"statusCode\":502,\"status\":502,\"message\":\"'500' is not an expected status code.\",\"originalRequest\":{\"uri\":\"/our-demo-project/payments/9ff06372-4812-4293-916b-01c58864c056\",\"method\":\"POST\",\"body\":{\"version\":101,\"actions\":[{\"action\":\"addInterfaceInteraction\",\"type\":{\"key\":\"ctp-adyen-integration-interaction-notification\",\"typeId\":\"type\"},\"fields\":{\"createdAt\":{},\"status\":\"AUTHORISATION\",\"notification\":\"{\\\"NotificationRequestItem\\\":{\\\"additionalData\\\":{\\\"expiryDate\\\":\\\"10/2020\\\",\\\"authCode\\\":\\\"39697\\\",\\\"cardSummary\\\":\\\"1142\\\"},\\\"amount\\\":{\\\"currency\\\":\\\"EUR\\\",\\\"value\\\":495},\\\"eventCode\\\":\\\"AUTHORISATION\\\",\\\"eventDate\\\":\\\"2019-07-03T19:19:30+02:00\\\",\\\"merchantAccountCode\\\":\\\"CommercetoolsGmbHDE775\\\",\\\"merchantReference\\\":\\\"paymentReferenceId\\\",\\\"operations\\\":[\\\"CANCEL\\\",\\\"CAPTURE\\\",\\\"REFUND\\\"],\\\"paymentMethod\\\":\\\"visa\\\",\\\"pspReference\\\":\\\"853562174370815K\\\",\\\"reason\\\":\\\"39697:1142:10/2020\\\",\\\"success\\\":\\\"true\\\"}}\"}}]},\"headers\":{\"Accept\":\"application/json\",\"Content-Type\":\"application/json\",\"Authorization\":[\"Bearer ********\"]}},\"retryCount\":0,\"headers\":{\"server\":[\"nginx\"],\"date\":[\"Fri, 05 Jul 2019 22:04:19 GMT\"],\"content-type\":[\"application/json; charset=utf-8\"],\"content-length\":[\"337\"],\"x-http-status-caused-by-extension\":[\"true\"],\"server-timing\":[\"projects;dur=74\"],\"x-correlation-id\":[\"projects-c055bbda-12ee-45d2-9b53-09e9f02fc4a4\"],\"x-served-by\":[\"api-gce-bf772e57.sphere.prod.commercetools.de\"],\"x-served-config\":[\"sphere-projects-ws-1.0\"],\"access-control-allow-origin\":[\"*\"],\"access-control-allow-headers\":[\"Accept, Authorization, Content-Type, Origin, User-Agent\"],\"access-control-allow-methods\":[\"GET, POST, DELETE, OPTIONS\"],\"access-control-max-age\":[\"299\"],\"via\":[\"1.1 google\"],\"alt-svc\":[\"clear\"],\"connection\":[\"close\"]},\"body\":{\"statusCode\":502,\"message\":\"'500' is not an expected status code.\",\"errors\":[{\"code\":\"ExtensionBadResponse\",\"message\":\"'500' is not an expected status code.\",\"extensionErrors\":[],\"extensionBody\":\"\",\"extensionStatusCode\":500,\"extensionId\":\"42ffdeb9-70c7-4630-b033-3de4b91886f2\",\"extensionKey\":\"ctp-adyen-integration-payment-extension\"}]},\"name\":\"HttpError\",\"stack\":\"HttpError: '500' is not an expected status code.\\n    at createError (/app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:236:10)\\n    at /app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:341:25\\n    at <anonymous>\\n    at process._tickCallback (internal/process/next_tick.js:189:7)\"}",
      "stack": "Error: Unexpected error during updating a payment with ID: 9ff06372-4812-4293-916b-01c58864c056. Exiting. Error: {\"code\":502,\"statusCode\":502,\"status\":502,\"message\":\"'500' is not an expected status code.\",\"originalRequest\":{\"uri\":\"/our-demo-project/payments/9ff06372-4812-4293-916b-01c58864c056\",\"method\":\"POST\",\"body\":{\"version\":101,\"actions\":[{\"action\":\"addInterfaceInteraction\",\"type\":{\"key\":\"ctp-adyen-integration-interaction-notification\",\"typeId\":\"type\"},\"fields\":{\"createdAt\":{},\"status\":\"AUTHORISATION\",\"notification\":\"{\\\"NotificationRequestItem\\\":{\\\"additionalData\\\":{\\\"expiryDate\\\":\\\"10/2020\\\",\\\"authCode\\\":\\\"39697\\\",\\\"cardSummary\\\":\\\"1142\\\"},\\\"amount\\\":{\\\"currency\\\":\\\"EUR\\\",\\\"value\\\":495},\\\"eventCode\\\":\\\"AUTHORISATION\\\",\\\"eventDate\\\":\\\"2019-07-03T19:19:30+02:00\\\",\\\"merchantAccountCode\\\":\\\"CommercetoolsGmbHDE775\\\",\\\"merchantReference\\\":\\\"paymentReferenceId\\\",\\\"operations\\\":[\\\"CANCEL\\\",\\\"CAPTURE\\\",\\\"REFUND\\\"],\\\"paymentMethod\\\":\\\"visa\\\",\\\"pspReference\\\":\\\"853562174370815K\\\",\\\"reason\\\":\\\"39697:1142:10/2020\\\",\\\"success\\\":\\\"true\\\"}}\"}}]},\"headers\":{\"Accept\":\"application/json\",\"Content-Type\":\"application/json\",\"Authorization\":[\"Bearer ********\"]}},\"retryCount\":0,\"headers\":{\"server\":[\"nginx\"],\"date\":[\"Fri, 05 Jul 2019 22:04:19 GMT\"],\"content-type\":[\"application/json; charset=utf-8\"],\"content-length\":[\"337\"],\"x-http-status-caused-by-extension\":[\"true\"],\"server-timing\":[\"projects;dur=74\"],\"x-correlation-id\":[\"projects-c055bbda-12ee-45d2-9b53-09e9f02fc4a4\"],\"x-served-by\":[\"api-gce-bf772e57.sphere.prod.commercetools.de\"],\"x-served-config\":[\"sphere-projects-ws-1.0\"],\"access-control-allow-origin\":[\"*\"],\"access-control-allow-headers\":[\"Accept, Authorization, Content-Type, Origin, User-Agent\"],\"access-control-allow-methods\":[\"GET, POST, DELETE, OPTIONS\"],\"access-control-max-age\":[\"299\"],\"via\":[\"1.1 google\"],\"alt-svc\":[\"clear\"],\"connection\":[\"close\"]},\"body\":{\"statusCode\":502,\"message\":\"'500' is not an expected status code.\",\"errors\":[{\"code\":\"ExtensionBadResponse\",\"message\":\"'500' is not an expected status code.\",\"extensionErrors\":[],\"extensionBody\":\"\",\"extensionStatusCode\":500,\"extensionId\":\"42ffdeb9-70c7-4630-b033-3de4b91886f2\",\"extensionKey\":\"ctp-adyen-integration-payment-extension\"}]},\"name\":\"HttpError\",\"stack\":\"HttpError: '500' is not an expected status code.\\n    at createError (/app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:236:10)\\n    at /app/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:341:25\\n    at <anonymous>\\n    at process._tickCallback (internal/process/next_tick.js:189:7)\"}\n    at updatePaymentWithRepeater (/app/src/handler/notification/notification.handler.js:45:15)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)",
      "name": "Error"
    },
    "pid": 22,
    "msg": "Unexpected exception occurred."
  },
  "resource": {
    "type": "container",
    "labels": {
      "xxx": "xxx"
    }
  },
  "timestamp": "2019-07-05T22:04:19.627Z",
  "severity": "INFO",
  "labels": {
    "xxx": "xxx"
  },
  "logName": "xxx",
  "receiveTimestamp": "2019-07-05T22:04:32.033121670Z"
}
```

**Comment by butenkor** [comment]
Hi @lojzatran. This error is actually caused by extension module and thus prevents notification module from adding the interaction, right?

It might be useful in case of 5xx errors to log whole payment and not just payload with actions, wdyt?

**Comment by lojzatran** [comment]
I tried the action in impex and got this error back:
```
{
  "statusCode": 400,
  "message": "The value '{}' is not valid for field 'createdAt'. ",
  "errors": [
    {
      "code": "InvalidField",
      "message": "The value '{}' is not valid for field 'createdAt'. ",
      "action": {
        "action": "addInterfaceInteraction",
        "type": {
          "typeId": "type",
          "key": "ctp-adyen-integration-interaction-notification"
        },
        "fields": {
          "createdAt": {},
          "status": "AUTHORISATION",
          "notification": "{\"NotificationRequestItem\":{\"additionalData\":{\"expiryDate\":\"10/2020\",\"authCode\":\"39697\",\"cardSummary\":\"1142\"},\"amount\":{\"currency\":\"EUR\",\"value\":495},\"eventCode\":\"AUTHORISATION\",\"eventDate\":\"2019-07-03T19:19:30+02:00\",\"merchantAccountCode\":\"CommercetoolsGmbHDE775\",\"merchantReference\":\"paymentReferenceId\",\"operations\":[\"CANCEL\",\"CAPTURE\",\"REFUND\"],\"paymentMethod\":\"visa\",\"pspReference\":\"853562174370815K\",\"reason\":\"39697:1142:10/2020\",\"success\":\"true\"}}"
        }
      },
      "actionIndex": 1,
      "invalidValue": {},
      "field": "createdAt"
    }
  ]
}
```

In the error above, it is indeed 500 error from extension, but I cannot reproduce this behaviour. However, the root cause here is the empty createdAt, which should not be sent at all. Once we solve it, we can check for other errors.

**Comment by lojzatran** [comment]
I investigated this error on my local machine and found out the following:
1) Missing value `{}` for `createdAt` is just a log issue. We pass `createdAt: new Date()` as an action to ctpClient and somehow when we got an error back, this is being displayed as `createdAt: {}`. This I solved by passing `createdAt: new Date().toISOString()` instead. So when we create an action from notification module, we pass the correct date value, but the logging for error just displays it wrong.
2) The real problem lies in extension module. We got this error:
```
"Unexpected token , in JSON at position 32518\\\",\\\"stack\\\":\\\"SyntaxError: Unexpected token , in JSON at position 32518\\\\n    at JSON.parse (<anonymous>)\\\\n    at _getPaymentObject (/app/src/api/payment/payment.controller.js:53:30)
```
The error is in this line `const requestBody = JSON.parse(body)` from this method:
```js
async function _getPaymentObject (request) {
  const body = await httpUtils.collectRequestData(request)
  try {
    const requestBody = JSON.parse(body)
    return requestBody.resource.obj
  } catch (err) {
    throw new Error(`Error during parsing CTP request: '${body}'. Ending the process. `
      + `Error: ${JSON.stringify(serializeError(err))}`)
  }
}
```
So this means that the request does not contain complete JSON and cannot be parsed. However, when I tested on my local, there was no error. I tried multiple times and they all returned correct results.

**Comment by butenkor** [comment]
It cannot be reproduced anymore.
